# 端口配置
server:
  port: 11002
# 数据库配置
spring:
  application:
    name: book-server
  # mysql数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=true&serverTimezone=UTC
    username: root
    password: ssx14233

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:11000/eureka/


# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打开SQL日志文件输出在控制台
  global-config:
    db-config:
      id-type: auto # 全局的id生成策略
  mapper-locations: classpath:mapper/*Mapper.xml # 加载xml映射文件
  type-aliases-package: com.tionkior.springcloudbookservice.entity # 设置别名

env: test
